### ISSUE TITLE
No support for ES2020?

### ISSUE THREAD

**Issue by EmptyDreams** [terser/html-minifier-terser#139] opened 2022-12-04 12:37 UTC
When I inline the HTML `<script></script>` with `?.`, `html-minifier-terse` will skip the compression of that element directly.

For example.

```html
<html>
<script>
    (() => {
        const sw = navigator.serviceWorker
        const error = () => {}
        if (!sw?.register('/sw.js')?.then(() => {
            if (!sw.controller) location.reload()
        })?.catch(error)) error()
    })()
</script>
</html>
```

After compression, it will look like the following.

```html
<html><script>(() => {
        const sw = navigator.serviceWorker
        const error = () => {}
        if (!sw?.register('/sw.js')?.then(() => {
            if (!sw.controller) location.reload()
        })?.catch(error)) error()
    })()</script></html>
```

If I put all the `?.` are replaced by `.` will be compressed properly, like this below.

```html
<html><script>(()=>{const r=navigator.serviceWorker,e=()=>{};r.register("/sw.js").then(()=>{r.controller||location.reload()}).catch(e)})()</script></html>
```

**Comment by DanielRuf** [comment] 2022-12-04 12:55
Thanks for reporting this.

Since the js compression logic comes from terser, I suggest testing if a newer terser version fixes this.

This bug should be reported at https://github.com/terser/terser/issues so I'm going to close this one here.

Please linke the terser issue here then so we can check what we will have to do then.

**Closed by DanielRuf** 2022-12-04 12:55 UTC

**Comment by EmptyDreams** [comment] 2022-12-04 14:58
> Thanks for reporting this.
> 
> Since the js compression logic comes from terser, I suggest testing if a newer terser version fixes this.
> 
> This bug should be reported at https://github.com/terser/terser/issues so I'm going to close this one here.
> 
> Please linke the terser issue here then so we can check what we will have to do then.

But another gulp plugin "gulp-terser" can compress this JS correctly, it uses `terser@5.9.0`.

**Comment by DanielRuf** [comment] 2022-12-04 15:19
In html-minifier-terser a newer version is used: https://github.com/terser/html-minifier-terser/blob/master/package.json#L83

Also at https://terser.org/html-minifier-terser/ I can not reproduce your problem.

Please double-check the version of html-minifier-terser that you use, and its configuration.

**Comment by EmptyDreams** [comment] 2022-12-05 07:04
> Please double-check the version of html-minifier-terser that you use, and its configuration.

The version of 'html-minifer-terser' I used is' 6.0.1 'with the following configuration:

```
minifyJS: true,
minifyCSS: true
```

**Comment by EmptyDreams** [comment] 2022-12-05 07:08
> Please double-check the version of html-minifier-terser that you use, and its configuration.

I'm sorry to trouble you. When I used ncu to check for updates, I did not check for the new version. I thought I was using the latest version, and the problem no longer existed after the update.

**Comment by DanielRuf** [comment] 2022-12-05 12:19
> the problem no longer existed after the update

Perfect, thanks for the update. If there are any other obstacles, please let us know in separate issues.

**Comment by DanielRuf** [comment] 2022-12-05 12:25
> I'm sorry to trouble you.

Everything is fine. I just had a rough week.

Besides that maybe it would be helpful to make clear in an issue template what version of html-minifier-terser is used and mention that the js compression part is solely handled by terser.

So if new issues appear in the latest version of html-minifier-terser it might be hlpful to point users to the bugtracker of terser to clarify things there first.

If the issues can then be solved by either updating terser on our side or adjusting its configuration used by us, then we can do the relevant changes and prepare a new release.

What do you think @sibiraj-s?

**Comment by sibiraj-s** [comment] 2022-12-07 17:08
Yes. That would be a great idea. It should deflect to the right place/solution to some of the issues which you have mentioned.

Let me add an issue template for this.

**Comment by EmptyDreams** [comment] 2022-12-12 00:48
I apologize for not being able to respond to you in a timely manner, as I have been ill recently.

I'm glad I could provide some minor help in refining the question template.

I think it's a very good idea to add some templates that tell users what information they need to provide and include a reminder to double-check the version they're using at github.

But I don't quite understand what you mean by "What do you think sibiraj-s".
