### ISSUE TITLE
Text between "<%" and "%>" not minified in script tag

### ISSUE THREAD

**Issue by huahuahu** [terser/html-minifier-terser#120] opened 2022-03-26 09:32 UTC
**Bug report or Feature request?**
Bug Report

**Version**
```
npx html-minifier-terser -V
7.0.0-alpha.2
```

**Complete CLI command or `minify()` options used**

```
{
  removeAttributeQuotes: true,
  minifyJS: {
    format: {
        ascii_only: true,
    },
  },
}
```
**input**
```
'<script>consolg.log("<%你好%> 你好")</script><p title="blah" id="moo">foo</p>'
```
**output or error**
```
<script>consolg.log("<%你好%> \u4f60\u597d")</script><p title=blah id=moo>foo</p>
```
**Expected result**
```
<script>consolg.log("<%\u4f60\u597d%> \u4f60\u597d")</script><p title=blah id=moo>foo</p>
```

**Comment by huahuahu** [comment] 2022-03-26 09:38
I think the reason is that the "<%你好%>" is treated as customFragment [here](https://github.com/terser/html-minifier-terser/blob/4f51a6ae77a118b0d4c58a16285493e1614043ea/src/htmlminifier.js#L891)

<img width="462" alt="image" src="https://user-images.githubusercontent.com/5757671/160233793-b3285985-14aa-4be9-8c7c-3179384fbc56.png">

**Comment by DanielRuf** [comment] 2022-03-26 10:27
Hi @huahuahu,

correct. There is a setting for this: `ignoreCustomFragments`

Not a bug but a feature since this was set by default for several and good reasons.

**Comment by DanielRuf** [comment] 2022-03-26 10:30
Closing as this is not a bug but a feature. Please text with different settings for `ignoreCustomFragments`.

**Closed by DanielRuf** 2022-03-26 10:30 UTC
