### ISSUE TITLE
Setting minify-css or minify-js to false does not work as expected

### ISSUE THREAD

**Issue by wanjapflueger** [terser/html-minifier-terser#119] opened 2022-03-20 19:30 UTC
I am using [html-minifier-terser](https://www.npmjs.com/package/html-minifier-terser) in my _package.json_ with _Node_ 16.

In the [official documentation](https://www.npmjs.com/package/html-minifier-terser#usage) I found a _help_ command. Running this gives me a list of options:

```bash
html-minifier-terser --help
```

I found two options that could serve my needs:

```
--minify-css [value]                 Minify CSS in style elements and style attributes (uses clean-css)
--minify-js [value]                  Minify Javascript in script elements and on* attributes (uses terser)
```

The type of `[value]` is not defined – but since the sample command at [„Sample command line:”](https://www.npmjs.com/package/html-minifier-terser#usage) uses `--minify-js true` I assume that I can also use `--minify-js false`.

Sample command:

```bash
html-minifier-terser --collapse-whitespace --remove-comments --minify-js true
```

But whatever I do, using `--minify-js false` does not do the trick.

The commands that I run are:

```bash
html-minifier-terser --input-dir src --output-dir dist --minify-css true --minify-js true # input is the same as output. no minification happening.
html-minifier-terser --input-dir src --output-dir dist --collapse-whitespace --minify-css false --minify-js false # HTML, CSS and JavaScript is minified
html-minifier-terser --input-dir src --output-dir dist --collapse-whitespace # exactly same as above
```

I am using `--collapse-whitespace` since nothing happens when I don't.

I created a simple setup so it's easy to understand. In _src_ you will find a single HTML, CSS and JavaScript file. When running the command for the minification, the results are in _dist_.

[html-minifier-test.zip](https://github.com/terser/html-minifier-terser/files/8312012/html-minifier-test.zip)
[html-minifier-test_without-node_modules.zip](https://github.com/terser/html-minifier-terser/files/8312026/html-minifier-test_without-node_modules.zip)

Based on my assumptions and the provided code, the evolving questions are:

- Am I doing something wrong?
- Is this a bug or was this never a feature?
- Is there any way to avoid JavaScript or CSS files from being minified when running _html-minifer_?

Thank you very much for your time and responding!

Greetings from cologne!

**Comment by DanielRuf** [comment] 2022-03-20 19:48
Hi @wanjapflueger,

please see the note there:

https://github.com/terser/html-minifier-terser#usage

> Note that almost all options are disabled by default. Experiment and find what works best for you and your project.

**Comment by DanielRuf** [comment] 2022-03-20 19:49
You can see some enabled settings in the demo at https://terser.org/html-minifier-terser/

**Comment by wanjapflueger** [comment] 2022-03-23 10:34
Hi @DanielRuf ,

thank you for your quick reply!

Since `--minify-css [value]` is in the „list of available options”, I assume it is enabled and I can set it to `true` or `false`. Or am I wrong? 

In case the options `--minify-css` and `--minify-js` are disabled by default – how can I enable them when using the command line?

The documentation tells me to „experiment and find what works best” – but that is what I did (as stated in the issue above) and nothing worked at all.

Simplified from https://github.com/terser/html-minifier-terser/issues/119#issue-1174658448:

```bash
# I want to minify .html, .css and .js files in my directory → but nothing is happening
html-minifier-terser --minify-css true --minify-js true

# I want to minify .html files only but not .css and not .js files → but all files are being minified
html-minifier-terser --minify-css false --minify-js false --collapse-whitespace

# I do not specify what I want to be minified → all files are being minified
html-minifier-terser --collapse-whitespace
```

Thanks again!

**Comment by DanielRuf** [comment] 2022-03-23 12:49
I can not really follow. When you disable css and js minification, then only html minification is done. And for my case it works:

`npm i -g html-minifier-terser`

```patch
--- src/test.html	2022-03-23 13:44:53.950067915 +0100
+++ dist/test.html	2022-03-23 13:45:00.614017595 +0100
@@ -1,25 +1,9 @@
-<!DOCTYPE html>
-<html lang="en">
-<head>
-    <meta charset="UTF-8">
-    <meta http-equiv="X-UA-Compatible" content="IE=edge">
-    <meta name="viewport" content="width=device-width, initial-scale=1.0">
-    <title>Document</title>
-</head>
-<body>
-    <style>
-        .some-empty-selector {}
+<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Document</title></head><body><style>.some-empty-selector {}
         .some-selector {
             width: 0px;
             height: 0px;
-        }
-    </style>
-    <script>
-        console.log(true); console.log(
+        }</style><script>console.log(true); console.log(
             1,
             2,
             3
-        );
-    </script>
-</body>
-</html>
\ Kein Zeilenumbruch am Dateiende.
+        );</script></body></html>
\ Kein Zeilenumbruch am Dateiende.
```

Used test file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <style>
        .some-empty-selector {}
        .some-selector {
            width: 0px;
            height: 0px;
        }
    </style>
    <script>
        console.log(true); console.log(
            1,
            2,
            3
        );
    </script>
</body>
</html>
```

Please prove a clear reproducible testcase with some test files.

**Comment by DanielRuf** [comment] 2022-03-23 12:50
Your example commands use stdin and stdout. So these are probably not what you want to use.

**Comment by DanielRuf** [comment] 2022-03-23 13:03
This works for me without any issues:

`html-minifier-terser --input-dir src --output-dir dist --collapse-whitespace --minify-css false --minify-js false`

result:

```html
--- src/test.html	2022-03-23 13:44:53.950067915 +0100
+++ dist/test.html	2022-03-23 14:01:03.346747980 +0100
@@ -1,25 +1,9 @@
-<!DOCTYPE html>
-<html lang="en">
-<head>
-    <meta charset="UTF-8">
-    <meta http-equiv="X-UA-Compatible" content="IE=edge">
-    <meta name="viewport" content="width=device-width, initial-scale=1.0">
-    <title>Document</title>
-</head>
-<body>
-    <style>
-        .some-empty-selector {}
+<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Document</title></head><body><style>.some-empty-selector {}
         .some-selector {
             width: 0px;
             height: 0px;
-        }
-    </style>
-    <script>
-        console.log(true); console.log(
+        }</style><script>console.log(true); console.log(
             1,
             2,
             3
-        );
-    </script>
-</body>
-</html>
\ Kein Zeilenumbruch am Dateiende.
+        );</script></body></html>
\ Kein Zeilenumbruch am Dateiende.
```

Same for this:
`html-minifier-terser --input-dir src --output-dir dist --collapse-whitespace`

```html
--- src/test.html	2022-03-23 13:44:53.950067915 +0100
+++ dist/test.html	2022-03-23 14:02:31.502082317 +0100
@@ -1,25 +1,9 @@
-<!DOCTYPE html>
-<html lang="en">
-<head>
-    <meta charset="UTF-8">
-    <meta http-equiv="X-UA-Compatible" content="IE=edge">
-    <meta name="viewport" content="width=device-width, initial-scale=1.0">
-    <title>Document</title>
-</head>
-<body>
-    <style>
-        .some-empty-selector {}
+<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Document</title></head><body><style>.some-empty-selector {}
         .some-selector {
             width: 0px;
             height: 0px;
-        }
-    </style>
-    <script>
-        console.log(true); console.log(
+        }</style><script>console.log(true); console.log(
             1,
             2,
             3
-        );
-    </script>
-</body>
-</html>
\ Kein Zeilenumbruch am Dateiende.
+        );</script></body></html>
\ Kein Zeilenumbruch am Dateiende.
```

To apply the changes only to specific filetypes, please take a look at this:
> --file-ext <text>                    Specify an extension to be read, ex: html

**Comment by DanielRuf** [comment] 2022-03-23 13:08
# I want to minify .html, .css and .js files in my directory → but nothing is happening
html-minifier-terser --minify-css true --minify-js true

> works for me when I apply it to my testfile

# I want to minify .html files only but not .css and not .js files → but all files are being minified
html-minifier-terser --minify-css false --minify-js false --collapse-whitespace

> see the `--file-ext` option, please also take a look at cli.js

# I do not specify what I want to be minified → all files are being minified
html-minifier-terser --collapse-whitespace

> that is the correct default behavior:
https://github.com/terser/html-minifier-terser/blob/master/cli.js#L299
https://github.com/terser/html-minifier-terser/blob/master/cli.js#L259
https://github.com/terser/html-minifier-terser/blob/master/cli.js#L192

**Comment by DanielRuf** [comment] 2022-03-23 13:13
> I want to minify .html, .css and .js files in my directory → but nothing is happening
> html-minifier-terser --minify-css true --minify-js true

works for me when I apply it to my testfile, please keep in mind that it only parses and compresses html files and files where `<style>`  tags are found

> I want to minify .html files only but not .css and not .js files → but all files are being minified
> html-minifier-terser --minify-css false --minify-js false --collapse-whitespace

see the `--file-ext` option, please also take a look at cli.js

> I do not specify what I want to be minified → all files are being minified
> html-minifier-terser --collapse-whitespace

that is the correct default behavior:
https://github.com/terser/html-minifier-terser/blob/master/cli.js#L299
https://github.com/terser/html-minifier-terser/blob/master/cli.js#L259
https://github.com/terser/html-minifier-terser/blob/master/cli.js#L192

html-minifier-terser is meant to be run right after compilation as last step (like html-webpack-plugin works (they use html-minifier-terser)

**Comment by DanielRuf** [comment] 2022-03-26 10:29
Closing as everything works as expected. When css and js minification are disabled, the html-minifier only does the relevant changes and does not understand or parse js and css code in such cases.

**Closed by DanielRuf** 2022-03-26 10:29 UTC

**Comment by wanjapflueger** [comment] 2022-03-28 17:06
Hello @DanielRuf ,

thank you for your explanations!

I conclude:

`--minify-css true|false` and `--minify-js true|false` **only** apply to _JavaScript_ in [HTMLScriptElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement)s (`<script>`) and _CSS_ in [HTMLStyleElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement)s (`<style>`). As you point out in the comments above this works as expected.

However I was trying to minify **only files** with the extension 'html' (like _index.html_) in a directory containing with multiple file types like _HTML_, _CSS_ and _JavaScript_ files.

`--minify-css true|false` and `--minify-js true|false` does not affect JavaScript and CSS **files**. They will be minified regardless of the value (`true|false`).

`--file-ext` does that trick for me:

```bash
# minify only HTML files
html-minifier-terser --input-dir src --output-dir dist --collapse-whitespace --file-ext html
```

🙏 @DanielRuf please consider documenting `--file-ext [extension]` in [README.md](https://github.com/terser/html-minifier-terser/blob/master/README.md). Much appreciated!

**Comment by DanielRuf** [comment] 2022-03-28 19:18
> 🙏 @DanielRuf please consider documenting `--file-ext [extension]` in [README.md](https://github.com/terser/html-minifier-terser/blob/master/README.md). Much appreciated!
> 
> PS: You could also just paste the output of `html-minifier-terser --help` to the README.md.

The documentation currently only lists options for the JS API, not the CLI. Normally when you work with a CLI you use manpage / man <command> or append `--help`.

For the CLI we would need a separate section in the readme.
PRs which add such a section are very welcome.
