### ISSUE TITLE
[Bug]: Unable to delete all comments

### ISSUE THREAD

**Issue by EmptyDreams** [terser/html-minifier-terser#144] opened 2023-01-01 13:53 UTC
### What happened?

My configuration items are as follows:

```js
{
    removeComments: true
}
```

When I try to process the following HTML file:

```html
<!--#rightside-config-hideif hideArray
  +rightsideItem(hideArray)-->
```

`html-minifier-terser` does not remove the comments, I get the same output as the input.

### Version

V7.1.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Willing to submit a PR?

None

**Comment by DanielRuf** [comment] 2023-01-01 14:12
Thanks for reporting this.

I can confirm, that it does not wirk with this code. But with the following it seems to work:

```html
<!--rightside-config-hideif hideArray
  +rightsideItem(hideArray)-->
```

Will check in detail, why this happens.

**Comment by DanielRuf** [comment] 2023-01-01 14:28
Seems to be caused by `ignoreCustomComments` which is set to `[ /^!/, /^\s*#/ ]` by default.

See also https://github.com/terser/html-minifier-terser/blob/57504c4a75ad9a17f445f34ff8396aeeebe3679d/src/htmlminifier.js#L87-94 and https://github.com/terser/html-minifier-terser/blob/57504c4a75ad9a17f445f34ff8396aeeebe3679d/src/htmlminifier.js#L1252-1256.

That means all comments with `<!--(arbitrary amount of whitespace)#...-->` will not be removed by default.

Can you verify this?

**Comment by EmptyDreams** [comment] 2023-01-01 15:03
> 似乎是由默认设置为 BY 引起的。`ignoreCustomComments``[ /^!/, /^\s*#/ ]`
> 
> 另请参阅 https://github.com/terser/html-minifier-terser/blob/57504c4a75ad9a17f445f34ff8396aeeebe3679d/src/htmlminifier.js#L87-94 和 https://github.com/terser/html-minifier-terser/blob/57504c4a75ad9a17f445f34ff8396aeeebe3679d/src/htmlminifier.js#L1252-1256。
> 
> 这意味着默认情况下不会删除所有评论。`<!--(arbitrary amount of whitespace)#...-->`
> 
> 你能验证一下吗？

Removing the '#' does remove the comment. However, if you do not remove the '#', overriding 'ignoreCustomComments' still does not remove the comment.

**Comment by DanielRuf** [comment] 2023-01-01 19:50
`html-minifier-terser --remove-comments --ignore-custom-comments "" test.html` works for me.

This also removes the comment for me:

```json
{
    "removeComments": true,
    "ignoreCustomComments": []
}
```

`html-minifier-terser --config-file config.json test.html`

Tested with this in the html file:

```html
<!--#rightside-config-hideif hideArray
  +rightsideItem(hideArray)-->aaa
```

And it always returns `aaa`.

**Comment by DanielRuf** [comment] 2023-01-01 19:52
Closing as no reproducible steps were linked in the issue description and because I can not reproduce this with the CLI.

**Closed by DanielRuf** 2023-01-01 19:52 UTC
